# frozen_string_literal: true

source 'https://rubygems.org'

gem 'httparty', '~> 0.24.0'
gem 'workato-connector-sdk', '~> 1.3'

group :development, :test do
  gem 'pry', '~> 0.14'
  gem 'rspec', '~> 3.13'
  gem 'timecop', '~> 0.9'
  gem 'vcr', '~> 6.0'
  gem 'webmock', '~> 3.18'
  gem 'standard', '~> 1.53.0'
end